name: End-to-end tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  e2e-tests:
    name: End-to-end tests (e2e)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
          cache: 'npm'
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'

      - name: Install dependencies
        run: npm ci

      - name: Perform e2e tests with Heaful Puppeteer
        uses: maufrontier/puppeteer-headful-with-commands@v3
        env:
          CI: 'true'
        with:
          commands: npm test
